/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Kid": "孩子",
    "Quit daydreaming": "别做白日梦了",
    "∥LOCKED∥": "∥未解锁∥",
    "|Dojo, training area|": "|道场、训练区|",
    "Accessory": "配饰",
    "Autosave": "自动保存",
    "Body": "身体",
    "CLR": "明朗",
    "Clear": "清理",
    "BG Color": "背景色",
    "BG presets": "背景预设",
    "delete the save": "删除存档",
    "Destroy gradients": "取消渐变",
    "night": "夜间",
    "Location": "位置",
    "LOADING": "加载中",
    "Legs": "腿部",
    "Head": "头部",
    "Shield": "护盾",
    "WEP": "武器",
    "Weapon": "武器",
    "White": "白色",
    "special": "特殊",
    "settings": "设置",
    "save": "保存",
    "Resume the fight": "返回战斗",
    "R Arm": "右胳膊",
    "L Arm": "左胳膊",
    "R hand": "右手",
    "L hand": "左手",
    "Message log limit": "消息日志上限",
    "Nothing": "什么都没有",
    "Nothing here yet": "这里什么都没有",
    "OTHER": "其它",
    "Pause next battle": "暂停下一场战斗",
    "USE": "使用",
    "　stop combatlog　": "　停止战斗日志　",
    "　new": "　新",
    "\"<= Get up\"": "\"<= 起床\"",
    "\"Easiest\"": "\“最简单”",
    "\"Easy\"": "\"简单\"",
    "\"Normal\"": "\"正常\"",
    "\"Select the difficulty\"": "\"选择难度\"",
    "\"You are fighting training dummies\"": "\"你在和训练假人战斗\"",
    "(body": "(身体",
    "(R hand": "(右手",
    "|Your Home, Bed|": "|你的家，床|",
    "Monday": "周一",
    "load": "加载",
    "grey": "灰色",
    "hit chance": "命中率",
    "lvl:1 'Evil'": "等级:1 '邪恶'",
    "lvl:1 'Nobody'": "等级:1 '没人'",
    "m e s s a g e　　　l o g": "消息日志",
    "game not saved!": "游戏未保存！",
    "freeze messagelog　": "冻结消息日志",
    "FOD": "食物",
    "WPN": "武器",
    "(L hand": "(左手",
    "": "",
    "A Stick": "一根棍子",
    "Cure Grass": "治愈草",
    "EQP": "装备",
    "Game Saved": "游戏已保存",
    "Grab your stuff and get to it": "拿起你的东西，开始吧",
    "lvl:1 'Evil ♀'": "等级:1 '邪恶♀'",
    "New item obtained": "获得新物品",
    "saved...": "已保存...",
    "Wooden dummy": "木制假人",
    "Wooden dummy ->": "木制假人 ->",
    "Wooden dummy missed": "木假人未命中",
    "You": "你",
    "You ->": "你 ->",
    "You have training to complete": "您需要完成训练",
    "You missed": "你未命中",
    "\"A Stick\"": "\"一根棍子\"",
    "Class": "类型",
    "Club/Hammer, Blunt": "球杆/锤子，钝器",
    "Club/Hammer": "球杆/锤",
    "Medicine/Tool": "医药/工具",
    "Deletes": "删除",
    "health": "健康",
    "Herb with minor healing properties. Has to be processed before use. Can somewhat speed up recovery of tiny cuts and bruises if applied directly": "具有轻微治疗作用的草本植物。 使用前必须进行处理。 如果直接使用，可以在一定程度上加快微小伤口和瘀伤的恢复",
    "L arm": "左胳膊",
    "permanently": "永久",
    "R arm": "右胳膊",
    "Rarity": "稀有度",
    "Throw away": "丢弃",
    "Restores": "恢复",
    "Your favorite weapon!": "你最喜欢的武器！",
    "All": "全部",
    "Armor": "护甲",
    "Comestibles": "杂货",
    "Filter": "过滤",
    "Materials/Other": "材料/其他",
    "Weapons": "武器",
    "CRIT!": "暴击!",
    "(head": "(头部",
    "head": "头部",
    "lvl:1 'Evil ♂'": "等级:1 '邪恶♂'",
    "Material/Misc": "材料/杂项",
    "You have been knocked out...": "你被淘汰了...",
    "Looking at this fills you with bad memories": "看着这让你充满了不好的回忆",
    "Death Badge": "死亡徽章",
    "Awarded by fate for dying. Congratulations": "因死亡而被命运授予。 恭喜",
    "\"<= Go outside\"": "\"<= 出门\"",
    "\"Crash down and take a nap\"": "\“崩溃并小睡一会儿\”",
    "\"Examine basement door\"": "\"检查地下室门\"",
    "\"Examine Fireplace\"": "\"检查壁炉\"",
    "\"Examine your bag\"": "\"检查你的包\"",
    "\"Examine your hidden stash\"": "\"检查你隐藏的藏匿处\"",
    "|Your Home|": "|你的家|",
    "Foggy": "有雾",
    "Great way to pass time": "打发时间的好方法",
    "Sunny": "晴天",
    "Wednesday": "周三",
    "Your humble abode. You can rest here.": "你卑微的居所。 你可以在这里休息。",
    "\"<= Step away\"": "\"<= 走开\"",
    "\"Idea paper\"": "\"想法纸\"",
    "\"Retrieve spare firewood. You have a feeling you'll need it\"": "\"取回备用木柴。你有一种感觉，你会需要它\"",
    "\"Toss a stick into the fireplace\"": "\"把一根棍子扔进壁炉\"",
    "|Your Home, Fireplace|": "|你的家，壁炉|",
    "Bandana": "头巾",
    "Better take this with you": "最好随身携带这个",
    "Bread": "面包",
    "Comfy fireplace. You can warm up here if you light it up": "舒适的壁炉。 如果你点亮它，你可以在这里暖和",
    "Egg": "鸡蛋",
    "It's locked": "它是锁着的",
    "Milk": "牛奶",
    "Rice": "大米",
    "Something you've forgotten to grab before. There's a pack of food and some junk idea paper.": "以前忘记拿的东西。 有一包食物和一些垃圾想法纸。",
    "Wooden Sword": "木剑",
    "Water": "水",
    "\"Property Deed\"": "\“财产契约\”",
    "\"Throw a stick into the fireplace\"": "\"把一根棍子扔进壁炉\"",
    "\"Throw some firewood into the fireplace\"": "\"往壁炉里扔些柴火\"",
    "Comfy fireplace. You'll need fire if you want to get some cooking done": "舒适的壁炉。 如果你想完成一些烹饪，你需要火",
    "Firewood": "柴火",
    "Grab the contents": "抓取内容",
    "Woven Wallet": "编织钱包",
    "You have some lying around nearby": "你附近有一些",
    "You reach for a small red box which you keep your valuables in, it is time to take it out": "你伸手去拿一个红色的小盒子，里面放着贵重物品，是时候把它拿出来了",
    "You notice the fire flickering slightly": "你注意到火光在微微闪烁",
    "\"Famine\"": "\“饥荒\”",
    "Allows you to list and examine your possessions": "允许您列出和检查您的财产",
    "Book": "书",
    "Clean rice grains. Healthy and delicious when cooked, but awful to eat in dry state": "米粒洗净。 煮熟后健康美味，但在干燥状态下食用很糟糕",
    "Cloudy": "多云",
    "Drizzle": "细雨",
    "energy": "能量",
    "Food": "食物",
    "Food(": "食物(",
    "Never": "从不",
    "NEW PERK UNLOCKED": "新特权解锁",
    "New Skill Unlocked!": "新技能解锁！",
    "Night": "夜晚",
    "Overcast": "阴",
    "perishable": "易腐烂的",
    "Power potion for your bones": "为您的骨骼提供强力药水",
    "Rain": "雨天",
    "Read": "阅读",
    "Regular drinkable water": "普通饮用水",
    "Simple loaf of bread, baked with care. It's crunchy and smells nice": "简单的面包，小心烘烤。 它很脆，闻起来很香",
    "Simple long sword carved from light wood. Easy to handle and is suitable as amateurish training weapon": "用轻木雕刻而成的简单长剑。 易于操作，适合作为业余训练武器",
    "skills": "技能",
    "Sword": "剑",
    "Sword, Blunt": "剑、钝器",
    "Thin cloth bandana. It protects your face from sweat": "薄布头巾。 它可以保护你的脸免受汗水的侵害",
    "This is your personal wallet, you received it as a gift": "这是你的个人钱包，你收到了它作为礼物",
    "This old looking legal document indentifies you as a sole owner of this broken down hut you live in. It was passed down to you by your ancestors, you speculate": "这份看起来很旧的法律文件表明您是您居住的这座破房子的唯一所有者。您推测，这是您的祖先传给您的",
    "Thursday": "周四",
    "Tiny scrap of paper with information. You wrote it yourself to remember things.": "带有信息的小纸片。 你自己写的来记住事情。",
    "Tried": "尝试",
    "Whole chicken egg, very nutritious": "全蛋，非常有营养",
    "You can feel coinage inside": "你可以感觉到里面的硬币",
    "You took a sip": "你啜了一口",
    "\"=> Check the Message Board\"": "\"=> 查看留言板\"",
    "\"=> Approach the cat\"": "\"=> 接近猫\"",
    "\"=> Enter Dojo\"": "\"=> 进入道场\"",
    "\"=> Enter Southern forest\"": "\"=> 进入南方森林\"",
    "\"=> Enter Western Woods\"": "\"=> 进入西部森林\"",
    "\"=> Food stand\"": "\"=> 食品摊\"",
    "\"=> Go home\"": "\"=> 回家\"",
    "The rain feels surprisingly refreshing": "下雨的感觉出奇的清爽",
    "Village Center": "村中心",
    "Your clothes get soaked": "你的衣服湿透了 ",
    "\"=> Shady Kid\"": "\"=> 阴暗的孩子\"",
    "You have a feeling it might rain soon": "你有一种感觉可能很快就会下雨",
    "\"<= Go back\"": "\"<= 回去\"",
    "Bun with red beans added to it, resulting in rich flavour": "包子里加了红豆，味道浓郁",
    "\"<= Return\"": "\"<= 返回\"",
    "\"Pet the cat\"": "\"宠物猫\"",
    "Red Bean Bun": "红豆包",
    "Stormy": "暴风雨",
    "Street Merchant Ran: Welcome! What would you like?": "街头小贩冉：欢迎光临！ 你要什么？",
    "There is a cat.": "有一只猫。",
    "Village Center, Cat": "村中心，猫",
    "\"Explore the posts\"": "\“探索帖子\”",
    "Village Center, Street Food Stand": "村中心，街头小吃摊",
    "This is an advertisement for woven straw baskets": "这是一个编织草篮的广告",
    "Message Board": "留言板",
    "Village Center, Message Board": "村中心、留言板",
    "You can find jobs or other stuff here": "你可以在这里找到工作或其他东西",
    "\"Instructor: You got beaten up by an inanimated dummy?! Pay attention to your condition!\"": "\"教官：你被一个无生命的假人殴打了？！注意你的情况！\"",
    "|Dojo, lobby|": "|道场，大厅|",
    "Item Acquired": "物品获得",
    "This is an advertisement for carpentery supplies": "这是木工用品的广告",
    "Gate Guard: \"It is too dangerous for you to leave at this moment. Come back when you train a bit\"": "门卫：“你这个时候离开太危险了，训练一下再回来。”",
    "Gate Guard: \"Nothing for you to do there. Scram!\"": "门卫：\“在那里你无事可做。快滚！\”",
    "Lunar Phase": "月相",
    "Last Quarter Moon": "上弦月",
    "A single penny, outdated form of currency. For some reason it's still in circulation": "一分钱，过时的货币形式。 由于某种原因它仍在流通",
    "Dime": "一毛钱",
    "It will take you about": "它会花费大约",
    "minutes to finish": "分钟就可以完成",
    "Nickel": "镍",
    "Penny": "一分钱",
    "Quarter": "25美分硬币",
    "Round copper dime. Still shiny": "圆形铜币。 依旧闪亮",
    "Small nickel, outdated form of currency. It was worth much more in the past": "小镍币，过时的货币形式。 过去更值钱",
    "Very large coin, made of copper. Not much worth as money, but collected and used by poor blacksmiths for resmelting into tools": "非常大的硬币，由铜制成。 不值钱，但被贫穷的铁匠收集并用于重新熔炼成工具",
    "You are reading": "你在阅读",
    "A tiny useless stone, found everywhere. Can be thrown to create distraction": "一块无用的小石头，随处可见。 可以扔来分散注意力",
    "Bring money next time": "下次带钱来",
    "Hey, I've got some good stuff for you": "嘿，我有一些好东西给你",
    "Pebble": "卵石",
    "Piece of old stale bread covered in mold. Takes courage to eat": "一块被霉菌覆盖的陈旧面包。 吃东西需要勇气",
    "Spoiled Bread": "变质的面包",
    "Sorry you can't afford that!": "对不起，你买不起！",
    "Village Center, Child Trader": "村中心，儿童商人",
    "Training dummy": "训练假人",
    "Training dummy ->": "训练假人 ->",
    "You dry up": "你太渴了",
    "You passed out...": "你昏过去了...",
    "legs": "腿部",
    "\"Sleeping\"": "\“睡眠\”",
    "The rest of Body": "身体的其余部分",
    "Unremarkable someone trying to find his purpose in life": "一个不起眼的人试图找到他的人生目标",
    "You can't read while sleeping": "你不能在睡觉时阅读",
    "Ability to go by without any sustenance": "能够在没有任何食物的情况下通过",
    "Alphabetically": "按字母顺序",
    "by Amount": "按数量",
    "by Levels": "按等级",
    "by Type": "按类型",
    "EXP Gain +1%": "经验增益 +1%",
    "Export As File": "导出为文件",
    "Export As Text": "导出为文本",
    "Famine": "饥荒",
    "Import As Text": "通过文本导入",
    "Increases health gain during sleep": "增加睡眠期间的健康收益",
    "Increases lower energy effectiveness bonus": "增加较低的能量效率奖励",
    "Load File": "从文件加载",
    "LVL": "等级",
    "Nobody": "没有人",
    "Perks unlocked": "特权解锁",
    "S k i l l　　l i s t": "技能列表",
    "\"Bandana\"": "\“头巾\”",
    "\"Wooden Sword\"": "\"木剑\"",
    "(legs": "(腿部",
    "Dusk": "黄昏",
    "Friday": "周五",
    "Sleeping": "睡眠",
    "This is an advertisement for smithing orders": "这是铁匠铺的广告",
    "Yes": "是",
    "yes": "是",
    "\"Fighting\"": "\“战斗\”",
    "\"Pain Resistance\"": "\"抗痛性\"",
    "Skill": "技能",
    "Starry Night": "星夜",
    "Saturday": "周六",
    "You put one in your mouth...": "你把一颗放进嘴里...",
    " died": " 死亡了",
    " missed": " 未命中",
    "'Fighting'": "'战斗'",
    "Apple": "苹果",
    "Area cleared": "区域已清理",
    "It is too dangerous to read right now": "现在读书太危险了",
    "Juicy red fruit. Makes a fine breakfast if you have nothing else...": "多汁的红色水果。 如果你没有别的东西，做一顿美味的早餐......",
    "kills": "杀死",
    "lvl:2 'Nobody'": "等级:2 '没人'",
    "\"Instructor: Nice job kid! Here's the reward for completing the course\"": "\"教官：干得好！这是完成课程的奖励\"",
    "\"Instructor: Great job kid! Here's the reward for completing the course\"": "\"教官：干得好！这是完成课程的奖励\"",
    "\"Instructor: Nice work kid! Here's the reward for completing the course\"": "\"教官：干得好！这是完成课程的奖励\"",
    "Strand Of Straw": "稻草绳",
    "\"Sandals\"": "\“凉鞋\”",
    "Cheap unremarkable sandals made from light leather. Aren't even that comfortable to wear": "由轻质皮革制成的廉价平底凉鞋。 穿起来也不是很舒服",
    "Sandals": "凉鞋",
    "This fell out of a dummy when you punched it to death": "当你一拳打死它时，它从一个假人身上掉了下来",
    "You lost consciousness...": "你失去了知觉……",
    "You threw Clay Milk Cap into the distance": "你把粘土奶盖扔到远处",
    "Clay Milk Cap": "粘土奶盖",
    "Milk caps made from packed clay. Children like to play with these": "用粘土制成的奶盖。 孩子们喜欢玩这些",
    "Sunday": "周日",
    "The surroundings are flourishing with life, nothing bad can happen": "周围生机勃勃，没有什么不好的事情发生",
    "This is an advertisement for herbal medicine": "这是中草药的广告",
    "Training dummy died": "训练假人死了",
    "You hit Wooden dummy for": "你击中了木制人偶",
    "You hit Straw dummy for": "你击中了稻草人偶",
    "You hit Training dummy for": "你击中了训练假人",
    "'Pain Resistance'": "'抗痛'",
    "'Sword Mastery'": "'剑术精通'",
    "\"Stop reading\"": "\"停止阅读\"",
    "damage": "伤害",
    "Linen Vest": "亚麻背心",
    "New Title Earned!": "获得新称号！",
    "Training dummy missed": "训练假人未命中",
    "Wood Splint": "木夹板",
    "You're already reading": "你已经在阅读了",
    "Wooden dummy died": "木制假人死了",
    "\"Initiate\"": "\"开始\"",
    "\"Instructor: Good job kid! Here's the reward for completing the course\"": "\"教官：干得好！这是完成课程的奖励\"",
    "\"Instructor: Your training is over for today, you did well. As a reward, select one of these skill manuals to practice. The better your understanding, the stronger you will be in battle\"": "“教官：今天的训练结束了，你做得很好。作为奖励，选择这些技能手册之一进行练习。你的理解越好，你在战斗中就越强大”",
    "\"Practitioner Skillbook (Axes)\"": "\"修行者技能书（斧）\"",
    "\"Practitioner Skillbook (Hammers)\"": "\"修行者技能书（锤）\"",
    "\"Practitioner Skillbook (Knives)\"": "\"修行者技能书（刀）\"",
    "\"Practitioner Skillbook (Martial)\"": "\"修行者技能书（武术）\"",
    "\"Practitioner Skillbook (Spears)\"": "\"修行者技能书（矛）\"",
    "\"Practitioner Skillbook (Swords)\"": "\"修行者技能书（剑）\"",
    "\"Destroy more dummies\"": "\“摧毁更多的假人\”",
    "\"Dojo infoboard\"": "\"道场信息板\"",
    "\"Grab a serving of free food\"": "\“拿一份免费食物\”",
    "\"Instructor: Back already?\"": "\"指导员：回来了吗？\"",
    "\"Level Advancement\"": "\"等级提升\"",
    "\"Turn in dojo gear\"": "\“道场装备回收\”",
    "\"Pamphlet\"": "\“小册子\”",
    "P Skillbook (Swords": "P 技能书（剑",
    "Paper Boy: Hey, this is for you!": "纸男孩：嘿，这是给你的！",
    "\"<= Return back into lobby\"": "\"<= 返回大厅 \"",
    "\"Claim your rewards!\"": "\“领取你的奖励！\”",
    "\"Get stronger!\"": "\“变强！\”",
    "\"Get your grub at the canteen!\"": "\“去食堂拿你的食物！\”",
    "\"Gluttony\"": "\“暴食\”",
    "\"Graduate!\"": "\"毕业了！\"",
    "\"Instructor: If you put effort into training you will get rewards as long as you are still a disciple of this hall. After every 5 levels you reach, come here and recieve your share! You might get something really useful if you continue to improve your skills\"": "\"教官：只要你努力修炼，只要你还是本堂弟子，就会得到奖励。每升5级，就来这里领取一份吧！继续练下去，说不定会得到真正有用的东西提高你的技能\"",
    "\"Instructor: You can return whatever you punched off of dummies and get coin for it, it's dojo's equipment after all. Or you can keep and use for it yourself, the choice is yours\"": "\"教官：你打出的假人什么的都可以退还给它，它毕竟是道场的装备。或者你可以自己保留和使用，选择权在你手中\"",
    "\"Measure your power!\"": "\“衡量你的力量！\”",
    "\"Return the rags\"": "v",
    "*Chow*": "* 周 *",
    "|Dojo, Infoboard|": "| 道场，信息板 |",
    "A little dry but, that will do": "有点干，但没关系",
    "Punch as many as you want": "打多少你想打多少",
    "Pieces of broken training dummies are scattered on the floor": "破碎的训练假人碎片散落在地板上",
    "Useful information regarding dojo is written here. What will you read?": "有关 道场 的有用信息写在此处。 你会读什么？",
    "You notice other dojo disciples diligently train": "你注意到其他道场弟子努力训练",
    "Physical Strength": "体力",
    "Power rank": "力量段位",
    "Speed": "速度",
    "This is you": "这是你",
    "This was shoved onto you by someone on the streets. Store names, discount prices, hot items... An entire wall of advertisements in tiny letters, to fit as much of it as possible on this piece of paper. It is a good idea to memorize the addresses": "这是街上有人推给你的。 商店名称、折扣价、热门商品……一整面小字母的广告墙，在这张纸上尽可能多地放上广告。 记住地址是个好主意",
    "'Literacy'": "'识字'",
    "\"Linen Vest\"": "\"亚麻背心\"",
    "\"Literacy\"": "\"识字\"",
    "\"Sword M\"": "\"剑术精通\"",
    "A small chipped piece of wood. Not very useful by itself": "一小块碎木头。 本身不是很有用",
    "Agility": "敏捷",
    "Allows for faster attacks and multihit combos": "允许更快的攻击和多重连击",
    "Current EXP Gain": "当前经验增益",
    "Determines hit/dodge rate": "决定命中率/闪避率",
    "Determines magic damage dealt and received": "决定造成和受到的魔法伤害",
    "Determines physical damage dealt and received": "决定造成和受到的物理伤害",
    "Empty space": "空的空间",
    "Energy Consumption Rate": "能源消耗率",
    "Energy Effectiveness": "能源效率",
    "Energy meter": "能量表",
    "Entry level practitioner skillbook about sword combat": "剑战入门级练功书",
    "EXP Gain Potential": "经验获得潜力",
    "Experience": "经验",
    "Fight dummies provided by dojo to improve your physique and weapon skills! Destroy them and grab their stuff, or vanquish thousands for a special reward! The doors of our dojo is open for everyone willing to lead the path of a warrio": "对抗道场提供的假人，提升你的体质和武器技能！ 摧毁他们并抢走他们的东西，或者征服数千人以获得特殊奖励！ 我们道场的大门向所有愿意引领勇士之路的人敞开",
    "Growth Potential": "成长潜力",
    "hours to finish": "小时去完成",
    "Influences the effectiveness of your actions, eat a lot to keep it full": "影响你行动的有效性，多吃以保持饱腹感",
    "\"Book\"": "\"书\"",
    "\"Meditation\"": "\“冥想\”",
    "Furniture": "家具",
    "Book which you've already read. It doesn't contain any new useful information": "你已经读过的书。 它不包含任何新的有用信息",
    "Current": "当前",
    "Furniture Acquired": "收购家具",
    "Health": "健康",
    "Mental acuity": "精神敏锐度",
    "owned": "拥有",
    "no": "否",
    "Physical and combat experience. You'll have to work hard to achieve new heights": "体力和战斗经验。 你必须努力工作才能达到新的高度",
    "Physical health points, needed to stay alive. You will probably die if it reaches 0": "维持生命所需的身体健康点数。 如果它达到0你可能会死",
    "Scrawny": "骨瘦如柴",
    "Use to add to the furniture list": "用于添加到家具列表",
    "You feel terrible. You might want to eat something or you'll end up being nothing more than a skeleton": "你觉得很可怕。 你可能想吃点东西，否则你最终只会成为一具骷髅",
    "Your power position in this realm. The lower the number the stronger you are": "你在这个领域的权力地位。 数字越小你越强",
    "Ability to fight using swords": "使用剑进行战斗的能力",
    "Ability to perform better in a fight": "在战斗中表现更好的能力",
    "Fighting": "战斗",
    "Ability to tolerate physical harm": "身体承受伤害的能力",
    "Gluttony": "暴食",
    "Improves reading speed": "提高阅读速度",
    "Literacy": "识字",
    "Mastery of eating": "掌握饮食",
    "SAT +5, HP +5, Gluttony EXP Gain +3%, New Title": "SAT +5，生命值 +5，暴食经验增益 + 3%，新称号",
    "Pain Resistance": "抗痛性",
    "Meditation": "冥想",
    "Slightly decreases damage received": "小幅减少受到的伤害",
    "Slightly increases attack power when holding a sword": "持剑时稍微增加攻击力",
    "Slightly increases overall attack power": "小幅提升整体攻击力",
    "Sword M lvl: ": "剑术精通 等级:",
    "Sword Mastery": "剑术精通",
    "The rest of Mind": "心灵的休息",
    "Understanding of meaning behind texts": "理解文本背后的意义",
    "\"Boiled Egg\"": "\“水煮蛋\”",
    "\"Boiled Rice\"": "\ “煮好的饭 \”",
    "\"Low-grade Healing Powder\"": "\"下品疗伤粉\"",
    "\"Straw Pendant\"": "\"稻草吊坠\"",
    "assemble": "工艺",
    "New blueprint unlocked": "新蓝图解锁",
    "! Get in time for your weekly menu!": "！ 及时了解您的每周菜单！",
    "\"Give it a try\"": "\“试一试\”",
    "As long as you keep gaining experience and train hard, dojo will provide you with gifts and money! Don't miss out!": "只要你不断积累经验并努力训练，道场就会为你提供礼物和金钱！ 不要错过！",
    "Boiled Rice": "煮好的饭",
    "Boiled Egg": "水煮蛋",
    "Fight dummies provided by dojo to improve your physique and weapon skills! Destroy them and grab their stuff, or vanquish thousands for a special reward! The doors of our dojo is open for everyone willing to lead the path of a warrior": "对抗道场提供的假人，提升你的体质和武器技能！ 摧毁他们并抢走他们的东西，或者征服数千人以获得特殊奖励！ 我们道场的大门向所有愿意引领勇士之路的人敞开",
    "Free Meals": "免费餐点",
    "Indestructable Dummy": "坚不可摧的假人",
    "Low-grade Healing Powder": "低品疗愈粉",
    "Our generous dojo provides": "我们慷慨的道场提供",
    "Straw Pendant": "稻草吊坠",
    "to every attending low-class disciple every": "给每一个在读的低阶弟子",
    "to measure the power of your fist!": "来衡量你拳头的力量！",
    "Try out punching this": "试试打这个",
    "When you are confident in your skills, try your fist at fighting powerful golems! How much beating can you withstand?": "当您对自己的技能充满信心时，请尝试与强大的傀儡战斗！ 你能承受多大的打击？",
    "\"Instructor: There's nothing I can take from you\"": "\"教官：我不能从你这里拿走什么\"",
    "\"Furniture list\"": "\"家具清单\"",
    "A \"bed\" made from several layers of straw placed onto each other. Extremely itchy and isn't much better from sleeping on a rock": "由相互叠放的几层稻草制成的“床”。 非常痒，睡在石头上也好不了多少",
    "Comfy fireplace. You can light it up for various useful means, or just to warm up": "舒适的壁炉。 你可以用各种有用的方式点亮它，或者只是为了热身",
    "Fireplace": "壁炉",
    "Furniture Owned": "自有家具",
    "Home rating": "房屋评级",
    "Straw Bedding": "稻草被褥",
    "'Gluttony'": "'暴食'",
    "This is an advertisement for bottled water": "这是瓶装水的广告",
    "Bandage": "绷带",
    "Hands": "手部",
    "Simple handwraps": "简单的裹手",
    "Perfect for morning runs": "晨跑的完美选择",
    "Dojo Pants": "道场裤",
    "\"Death\"": "\“死亡\”",
    "\"Bandage\"": "\“绷带\”",
    "Ability to cling to your fate": "把握命运的能力",
    "Death": "死亡",
    "Reduces energy loss on death": "减少死亡时的能量损失",
    "\"Aspiring Ronin\"": "\"有抱负的浪人\"",
    "\"Civilian\"": "\“平民\”",
    "1, AGL +1, New Title": "1、敏捷 +1、新称号",
    "Aspiring Ronin": "有抱负的浪人",
    "He's made of wood": "他是木头做的",
    "lvl:4 'Aspiring Ronin'": "",
    "Sword M": "剑术精通",
    "Wooden Knife": "木刀",
    "Watching swordplay of elder swordmasters always fascinated you, yet even trying to hold the sword properly is apparently extremely difficult. You are not the type to give up though": "看老剑客的剑法总是让你着迷，但即便是想要好好握剑，显然也是极其困难的。 你不是那种会放弃的人",
    "Lost kid's toy. The relic of many playground battles": "丢了孩子的玩具。 许多游乐场战斗的遗迹",
    "You'll feel chilly without sleeves": "不穿袖子会觉得冷",
    "He's made of straw": "他是稻草做的",
    "Knife": "刀",
    "'Knife Mastery'": "'刀法精通'",
    "\"Dojo Pants\"": "\"道场裤\"",
    "\"Knife M\"": "\"刀法精通\"",
    "\"Knife Mastery\"": "\"刀法精通\"",
    "\"Small Wood Bundle\"": "\"小木捆\"",
    "\"Starving Child\"": "\“饥饿的孩子\”",
    "\"Wooden Knife\"": "\"木刀\"",
    "Knife, Blunt": "刀, 钝的",
    "Equipment/Accessories": "装备/配饰",
    "Materials/Misc.": "材料/杂项",
    "Medicine/Tools": "医药/工具",
    "Nearby firesource": "附近火源",
    "output": "产出",
    "Prick": "刺",
    "reagents required": "所需材料",
    "Small Wood Bundle": "小木捆",
    "Steamed Rice": "蒸米饭",
    "tools needed": "需要的工具",
    "You found it fun to make little holes in plant leaves and look through them at the Sun. You think this could be morbidly useful in a fight": "你发现在植物叶子上打小洞并透过它们看太阳很有趣。 你认为这在战斗中可能非常有用",
    "TPE": "类型",
    "Straw Kasa": "草帽",
    "You're too busy fighting": "你太忙于战斗了",
    "A Sando-gasa is made by weaving straw together. Great for boys who are too embarrassed to use a parasol": "Sando-gasa是用稻草编织而成的。 非常适合那些不好意思使用遮阳伞的男孩",
    "to max energy": "达到最大能量",
    "You made this yourself!": "这是你自己做的！",
    "Ability to fight using knives and daggers": "使用刀和匕首进行战斗的能力",
    "Knife Mastery": "刀法精通",
    "Slightly increases attack power when holding a knife": "持刀时稍微增加攻击力",
    "1, New Title": "1, 新称号",
    "10, HP +5, New Title": "10, 生命值 +5, 新称号",
    "2, EXP Gain +1%": "2, 经验增益 +1%",
    "2%, AGL +1": "2%, 敏捷 +1",
    "5, HP +5": "5, 生命值 +5",
    "5, HP +5, Gluttony EXP Gain +3%, New Title": "5、生命值+5、暴食经验增加+3%、新称号",
    "Finely crushed cure grass. Used as a base to make weak medicine": "细碎的治疗草。 用作基剂制成弱药",
    "Type of dry wood, prepared for easy burning. Useful at camps or during winter": "干木类型，易于燃烧。 在营地或冬季有用",
    "\"Accept\"": "\"同意\"",
    "\"Instructor: This is a good start, congratulations! Keep working hard!\"": "\"指导员：这是一个好的开始，恭喜！继续努力！\"",
    "\"Level 5 reward\"": "\"5级奖励\"",
    "copper. How does that sound?\"": "铜。 听上去怎么样？\”",
    "Hit! Your approximate hand strength is measured in": "打！ 你大概的手部力量是用",
    "Low-grade Spirit Pill": "下品灵丹",
    "Punch! Your approximate hand strength is measured in": "冲！ 你大概的手部力量是用",
    "Slap! Your approximate hand strength is measured in": "拍击！ 你大概的手部力量是用",
    "Wham! Your approximate hand strength is measured in": "哇！ 你大概的手部力量是用",
    "You're out in the forest. You can hunt here": "你在森林里。 你可以在这里打猎",
    "You have been poisoned!": "你中毒了！",
    "You -> x2(": "你 -> x2(",
    "While coal is not easy to obtain around here, good burnable wood is always in demand. Your job this time is to collect and bring about 10 bundles of firewood, keep an eye out while you're strolling out in the forest. Your deed will help the villagers, and you will get something out of it as well": "虽然这里的煤炭并不容易获得，但优质的可燃木材总是很受欢迎。 这次你的工作是收集并带来大约10捆木柴，在森林漫步时留意。 你的行为会帮助村民，你也会从中得到一些东西",
    "Western Woods, The Wooden Gate": "西部森林，木门",
    "stabs you with something rusty": "用生锈的东西刺伤你",
    "Hm? Your face is unfamiliar. Might be your first time around here I take it? These are the Western Woods, or simply the western part of the forest. Spots here are very meek and mild on danger and resources, it is perfect for newbies like you. You are free to come and hunt as much as you like. Consider doing some of the available jobs while you're at it. Won't pay much, but you can be of help to the people.": "嗯？ 你的脸很陌生。 可能是你第一次来这里我接受它？ 这些是西部森林，或者干脆就是森林的西部。 这里的景点对危险和资源非常温和，非常适合像你这样的新手。 您可以随意来打猎。 当你在做一些可用的工作时，考虑一下。 不会付出太多，但你可以帮助人们。",
    "Here is what's available, take a look": "这是可用的，看看",
    "Head Hunter Yamato": "猎头大和",
    "Hack! Your approximate hand strength is measured in": "嗨！ 你大概的手部力量是用",
    "Delicious!": "美味！",
    "|Western Woods, Hunter's Lodge|": "|西部森林，猎人小屋|",
    "\"Tell me something\"": "\"告诉我一件事\"",
    "\"Refuse\"": "\“拒绝\”",
    "\"Hunting for meat\"": "\"狩猎肉类\"",
    "\"Firewood gathering\"": "\"柴火聚会\"",
    "\"=> Enter the Hunter's lodge\"": "\"=> 进入猎人小屋\"",
    "\"=> Delve inside the forest\"": "\"=> 深入森林\"",
    "\"<= Return back\"": "\"<= 返回\"",
    "\"<= Exit\"": "\"<= 退出\"",
    "\"!Ask about the jobs\"": "\"！询问工作\"",
    "A - Continental Threat": "A - 大陆威胁",
    "B - National Crisis": "B - 国家危机",
    "Beasts are your usual, normal wildlife like wolves, slimes, mimics, or prone to being evil Demihumans with low intelligence and high level of aggression like ogres, harpies, minotaurs. While animals are dumb, never underestimate a wild beast. With their thick skin and natural weapons like fangs and claws, they pose a major threat when driven into a desperate state. Fire works very well against the most, especially those with fur and feathers, keep that in mind next time you go hunting": "野兽是你平常的、正常的野生动物，如狼、史莱姆、模仿者，或者容易成为低智商和高侵略性的邪恶亚人，如食人魔、鹰身人、牛头怪。 虽然动物很笨，但永远不要低估野兽。 凭借厚厚的皮肤和尖牙利爪等天生武器，当他们被逼入绝境时会构成重大威胁。 火对大多数人都很有效，尤其是那些有毛皮和羽毛的人，下次去打猎时请记住这一点",
    "Beings that are artificially made or existences who are inherently evil, can be classified as such. Demons, imps, golems, possessed weapons and armor, gremlins, devils and much of anything else that comes out from the Underworld. They are extremely dangerous and seek destruction all that they come across": "人工制造的存在或本质上邪恶的存在，可以归类为此类。 恶魔、小鬼、傀儡、拥有的武器和盔甲、小鬼、恶魔以及来自冥界的任何其他东西。 他们非常危险，遇到的一切都寻求破坏",
    "D - Townside Crisis": "D - 城镇危机",
    "C - Citywide Crisis": "C - 全市危机",
    "Dragons are legendary creatures that possess evil and cunning intellect. Through some unknown means many dragons in ancient times were reduced to subspecies of wyverns and wyrms, or outright bastard draconids like lizardmen, and other beings with Dragon bloodline. The power of said bloodline grants them superior defence against magic and energy abilities, their physical toughness is also no joke": "龙是传说中的生物，拥有邪恶和狡猾的智慧。 通过某种未知的方式，古代的许多龙被降级为双足飞龙和巨龙的亚种，或者像蜥蜴人这样的混蛋龙类，以及其他具有龙血统的生物。 血脉之力，赋予了他们对魔法和能量能力的超强防御，他们的身体韧性也不是开玩笑",
    "E - Village Crisis": "E - 村庄危机",
    "F - Can be dealth with by male adults": "F - 可以由男性成年人处理",
    "G - Can be dealth with by able people": "G - 可以由有能力的人处理",
    "Grants +500 EXP": "授予 +500 经验",
    "Great! I will be awaiting your return": "伟大的！ 我会等待你的归来",
    "Human, Beast, Undead, Evil, Phantom, Dragon": "人、兽、亡灵、邪恶、幻影、龙",
    "Humans and Demihumans fall into the same class. People like you and me, beastmen, orcs, goblins... Mostly creatures intelligent enough to walk on their two, use tools, form societies, make settlements, trade and speak on their own violition. You will encounter and perhaps fight them as bandits, criminals, members of the opposing factions and armies, whoever you disagree with. Always be on your guard, humanoids are cunning and skilled, versatile and very adaptive. Yet, they have mushy bodies. One correct strike and you get an advantage": "人类和亚人属于同一阶级。 像你我这样的人，野兽人、兽人、地精……大多数是足够聪明的生物，它们可以在两个人的基础上行走，使用工具，组建社会，建立定居点，贸易和说话。 您会遇到并可能以土匪、罪犯、敌对派系和军队成员的身份与他们战斗，无论您不同意谁。 时刻保持警惕，类人生物狡猾而熟练，多才多艺且适应性强。 然而，他们有糊状的身体。 一次正确击球，您将获得优势",
    "If you find your task too difficult, go back to the training grounds": "如果你觉得你的任务太难了，回到训练场",
    "If you want to survive, you will need to eat. Prove that you can handle yourself in the wilderness by hunting down wildlife. 10 piece of fresh meat should be enough, bring them to me for the evaluation": "如果你想生存，你就需要吃饭。 证明您可以通过猎杀野生动物在荒野中应付自如。 10块鲜肉就够了，拿来给我评估",
    "Monsters, you say? There are many and they are around, terrorizing peaceful folk in the outside world. Our remote parts don't see much of that, these lands are tame. Not without dangers, of course, you meet a wild boar in the forest - a single wrong move and its tusks are in your guts and that is it, end of the fool. Or those pesky slimes, while don't look menacing and pose little danger, they sometimes gather and destroy the fields by melting crops and soil. We have it good but starvation is worse than any monster, at times. *cough* anyway, anything living and non-living you meet can be separated into 6 categories": "怪物，你说？ 有很多，他们就在身边，恐吓外面世界和平的人们。 我们的偏远地区很少看到这些，这些土地很温顺。 当然，并非没有危险，您在森林中遇到了一只野猪——一个错误的举动，它的象牙在你的胆子里，就是这样，傻瓜的结局。 或者那些讨厌的史莱姆，虽然看起来并不可怕，也不构成什么危险，但它们有时会通过融化庄稼和土壤来聚集和破坏田地。 我们有它，但饥饿有时比任何怪物都更糟糕。 *咳嗽*无论如何，你遇到的任何生物和非生物都可以分为6类",
    "Quest accepted": "接受任务",
    "No money - no goods! Don't waste my time!": "没钱——没货！ 不要浪费我的时间！",
    "Ranking is a way to separate monsters by their relative danger level, they go as following": "排名是一种根据怪物的相对危险等级来区分怪物的方法，它们如下",
    "S - Global Crisis": "S - 全球危机",
    "So you want something from the hidden stash, huh? Good eye! You are one of the dojo runts, I've got just what someone like you needs. One book, 3 silver": "所以你想从隐藏的藏匿处拿东西，是吗？ 好眼力！ 你是道场中的一员，我有像你这样的人需要的东西。 一本书，3银",
    "Souls of the dead, ethereal beings, manifestations of powers or other apparitions can all be called Phantoms. They take forms of wisp and sprites, benevolent or twisted elementals or spirits and wraiths that terrorize the living. They are difficult or sometimes outright impossible to hurt using normal physical means, magic or exorcism would be a preferred way of dealing with such enemies": "死者的灵魂，空灵的存在，力量的体现或其他幻影都可以称为幻影。 它们以精灵和精灵的形式出现，仁慈或扭曲的元素或精神和幽灵使生者感到恐惧。 使用正常的物理手段很难或有时完全不可能伤害它们，魔法或驱魔将是对付此类敌人的首选方式",
    "SS - World Disaster": "SS - 世界灾难",
    "SSS - Universal Calamity": "SSS - 普遍灾难",
    "The smell of beef jerky assaults your nose": "牛肉干的香味扑鼻而来",
    "Tiny cheap spirit pill, made from condensed Ki. Lowest type, given to weak people and children to nourish their bodies.": "小巧廉价的灵丹，由气凝聚而成。 最低的类型，给虚弱的人和孩子以滋养他们的身体。",
    "Undead, as you could already tell, are living dead. Reanimated remains of humans and beasts by the influence of natural forces or a skilled necromancer. Even if they completely lack intelligence and wander around aimlessly, controlled bodies of the dead get strenghtened by Dark magic and gain unnatural resilience and power as a result. It doesn't prevent them from being hurt by fire or Holy powers, hovewer. You can deal with lesser fragile skeletal beings quickly if you bash them with something blunt": "正如您已经知道的那样，不死生物正在死去。 在自然力量或熟练的死灵法师的影响下复活的人类和野兽的遗骸。 即使他们完全缺乏智慧，漫无目的地四处游荡，被控制的死者尸体也会被黑暗魔法强化，并因此获得不自然的弹性和力量。 但是，这并不能阻止他们受到火或神圣力量的伤害。 如果您用钝器猛击它们，您可以快速处理较不脆弱的骨骼生物",
    "We haven't experienced anything stronger than the E rank in all history of our village. Whatever is above the A rank is completely unheard of, and only partially mentioned in ancient texts. That's the realm of gods, world destroyers and higher beings that our mortal souls are unlikely to ever face": "在我们村的所有历史中，我们还没有经历过比E级更强的事情。 任何高于A级的都是闻所未闻的，在古代文本中也只是部分提及。 那是我们凡人的灵魂不可能面对的神界、世界毁灭者和高等生物的领域",
    "What do you want to ask, kid? Want to know how to butcher a carcass? Khahhahhah! *cough*": "你想问什么，孩子？ 想知道如何屠宰尸体吗？ 哈哈哈哈！ *咳嗽*",
    "You notice head hunter maintaining his hunting gear": "你注意到猎头在维护他的狩猎装备",
    "You see a variety of bows and other hunting tools arranged on the table and hanging from the walls": "你看到桌子上摆放着各种弓箭和其他狩猎工具，挂在墙上",
    ". So, watcha say?": ". 那么，怎么说呢？",
    "\"<= Nah\"": "\"<= 好吧\"",
    "\"♪La, laaaah, la, la-la. Lah, la-la,la la....♪\"": "\"♪ 啦，啦啦啦啦啦，啦，啦啦啦啦啦...♪\"",
    "\"About Beasts\"": "\"关于野兽\"",
    "\"About Dragons\"": "\"关于龙\"",
    "\"About Evil\"": "\"关于邪恶\"",
    "\"About Humans\"": "\“关于人类\”",
    "\"About monsters\"": "\"关于怪物\"",
    "\"About Phantoms\"": "\"关于幻影\"",
    "\"About Undead\"": "\"关于亡灵\"",
    "\"Firewood Gathering\"": "\"柴火聚会\"",
    "\"First Hunt\"": "\"第一次狩猎\"",
    "\"Oh my! Such pretty flowers♪\"": "\“天啊！好漂亮的花♪\”",
    "\"Give me\"": "\“给我\”",
    "\"Straw Basket\"": "\"草篮\"",
    "\"Show me something better\"": "\"给我看更好的东西\"",
    "\"What are monster ranks?\"": "\“什么是怪物等级？\”",
    "Straw Basket": "草篮",
    "That was good!": "那太好了！",
    "Green Slime": "绿色史莱姆",
    "Illiterate": "文盲",
    "Small woven basket. For storing stuff in": "小编织篮。 用于存放东西",
    "Ouch": "哎哟",
    "The woods are silent": "树林静悄悄",
    "Western Woods, The Yellow Path": "西部森林，黄色小径",
    "\"=> Visit Marketplace\"": "\"=> 访问市场\"",
    "\"<= Return back to the village Center\"": "\"<=返回村中心\"",
    "\"<= Walk away\"": "\"<= 走开\"",
    "\"General Store =>\"": "\"综合商店 =>\"",
    "\"Grocery Shop =>\"": "\"杂货店 =>\"",
    "\"Nervous Guy =>\"": "\"神经质的家伙 =>\"",
    "\"Purchase\"": "\"购买\"",
    "|Marketplace, Grocery Shop|": "|市场、杂货店|",
    "|Marketplace, Shabby General Store|": "|市场，破旧的综合商店|",
    "A length of sturdy rope, for tying things up": "一根结实的绳子，用来绑东西",
    "A poor quality swatch of cloth. Unstitches when you so much as breathe on it": "劣质布样。 当你呼吸到它的时候就解开缝线",
    "A small quantity of thread that could be used in sewing and tailoring projects": "少量可用于缝纫和裁缝项目的线",
    "Argh, what am I gonna do now! How could this... Uh? S-sorry, can't talk right now, please leave me be. Ahh damn it...\"": "啊，我现在该怎么办！ 这怎么可能……呃？ S-对不起，现在不能说话，请让我呆着。 啊该死的……\”",
    "Barely reached the standard, maybe you should keep it for longer": "勉强达到标准，也许你应该保持更长时间",
    "Cheap massproduced tableware carved from wood. Kind of a pain to wash": "廉价的大量生产的木雕餐具。 洗起来有点痛",
    "Cheap Cloth": "廉价布料",
    "General Store": "综合商店",
    "Gluttony EXP gain +5": "暴食经验增益 +5",
    "Marketplace, Stalls": "市场, 摊位",
    "Grocery Shop": "杂货店",
    "Nervous Guy": "紧张的家伙",
    "Old Lady: Freshest vegetables for the lowest price!": "老太太：最新鲜的蔬菜，最低的价格！",
    "Old Lady: These are very fresh, buy some!": "老太太：这些很新鲜，买一些吧！",
    "Old Lady: Try a few and you'll want even more!": "老太太：尝试一些，你会想要更多！",
    "One-year Wine": "一年酒",
    "Onion": "洋葱",
    "Raw wheat. While not very tasty, powder made out of them is the main ingredient in breadmaking": "生小麦。 虽然不是很好吃，但用它们制成的粉末是面包制作的主要成分",
    "Rock salt crushed into tiny crystals. Yuck! You surely wouldn't want to eat this. It's good for preserving perishable foods and cooking, though": "岩盐粉碎成微小的晶体。 糟糕！ 你肯定不想吃这个。 不过，它有利于保存易腐烂的食物和烹饪",
    "Rope": "绳子",
    "Salt": "盐",
    "Sleeping Old Man: ...": "沉睡的老人：...",
    "Sleeping Old Man: zzz...": "沉睡的老人：zzz...",
    "Tailoring quality": "剪裁质量",
    "The man then proceeds to fidget in unrest": "该男子随后在不安中坐立不安",
    "The marketplace feels busy": "市场感觉很忙",
    "Thread": "线",
    "Vegetable cultivated since ancient times. Enhances the dish in various ways, also makes you cry": "自古栽培的蔬菜。 以各种方式增强菜肴，也让你哭泣",
    "Very primitive needle crafted from tough wood. Despite its simplicity, the craftsmanship is quiet nice": "用坚韧的木头制成的非常原始的针。 尽管它很简单，但工艺却很安静",
    "Village Center, Marketplace": "村中心、市场",
    "Wheat": "小麦",
    "Wooden Needle": "木针",
    "Wooden Tableware": "木制餐具",
    "This is an advertisement for farming equipment": "这是农业设备的广告",
    "Tuesday": "周二",
    "went bad!": "变坏了！",
    "Your": "你的",
    "Your stomach bothers you": "你的胃让你烦恼",
    "Ability to absorb Air Ki and assimilate it within your body": "能够吸收气气并将其吸收到体内",
    "Air Absorption": "空气吸收",
    "Provides minor protection from air-based attacks": "对空中攻击提供轻微的保护",
    "\"Can I tag along? I won't be a bother♪\"": "\“我可以跟着吗？我不会打扰的♪\”",
    "Blunt Sword": "钝剑",
    "Crude planks cobbled together to form a container for a matress or such. Not a whole lot in terms of sleeping place, but somewhat better than a hard cold floor": "粗木板拼凑在一起，形成一个用于放置床垫等的容器。 睡觉的地方不是很多，但比硬冷的地板好一些",
    "Plain Bed": "普通床",
    "Rain Cap": "雨帽",
    "Rain Shoes": "雨鞋",
    "Simple shoes made from tree rubber. Sturdy and longlasting, they protect one's toes from cold": "由树胶制成的简单鞋子。 坚固耐用，保护脚趾免受寒冷",
    "The cap with the wide brim for keeping the rain from the wearer's eyes": "宽檐帽可防止雨水进入佩戴者的眼睛",
    "This is the blunt sword used as a bad example of a knife in demonstration sales for housewives. Good luck trying to cut onions with this": "这是在家庭主妇的示范销售中用作刀的坏例子的钝剑。 祝你用这个切洋葱好运",
    "Wastebread": "面包屑",
    "When flour becomes a commodity to deal with, wayfarers and the poor resort to mix it with leftovers of other ingredients and bake it all into bread": "当面粉成为一种需要处理的商品时，流浪者和穷人将其与其他成分的剩菜混合，然后全部烤成面包",
    "You have a really difficult time understanding even the basic writings. Even the signs outside the shops give you trouble": "即使是基本的著作，你也很难理解。 连店外的招牌都给你添麻烦",
    "Sleeping Old Man: ...Welcome": "沉睡的老人：......欢迎",
    "This is a warning to stay away from fortune tellers": "这是远离算命先生的警告",
    "Sleeping Old Man: Take your time": "沉睡的老人：慢慢来",
    "Watery leaves, usually used in salads": "水汪汪的叶子，通常用于沙拉",
    "Lettuce": "生菜",
    "\"Eat flowers evil-doer!♪\"": "\"吃花坏人！♪\"",
    "\"...deal!...\"": "\“...成交！...\”",
    "10, HP +5, Survival EXP Gain +5%": "10、生命值+5、生存经验获得+5%",
    "2%, New Title": "2%, 新称号",
    "Green Slime": "绿色史莱姆",
    "Blue Slime": "蓝色史莱姆",
    "Blue": "蓝色",
    "Green": "绿色",
    "Can't see a meter in front of you with all this fog": "迷雾重重，看不到你面前的一米",
    "It doesn't seem very sturdy": "看起来不是很坚固",
    "Wild Rabbit": "野兔",
    "Wild Rabbit ->": "野兔 ->",
    "Wild Rabbit -> x2(": "野兔 -> x2(",
    "\"...check for yourself then...\"": "\"...然后自己检查一下...\"",
    "We're restocking, step out for a minute": "我们正在补货，出去一会儿",
    "Ability to evaluate your choices": "评估您的选择的能力",
    "Judgement": "判断",
    "Rainy Night": "雨夜",
    "\"...is this real?...\"": "\“...这是真的吗？...\”",
    "\"...never seen this thing...\"": "\"...从没见过这个东西...\"",
    "\"...right, I'll take 10, put them in...\"": "\"...对了，我取10个，放进去...\"",
    "\"...this isn't even fresh!...\"": "\"...这甚至都不新鲜！...\"",
    "\"...whatever, I'm not buying...\"": "\"...无论如何，我不买...\"",
    "\"...who said so? Gotta be a lie...\"": "\"......谁说的？一定是谎言......\"",
    "\"Judgement\"": "\“判断\”",
    "\"All the children must return home by 8PM!\"": "\“所有孩子必须在晚上8点前回家！\”",
    "\"If you do not work your hours daily, you will not get any dessert\"": "\“如果你每天不加班，你就得不到任何甜点\”",
    "There is a section of useless gossip": "有一段没用的八卦",
    "This is an advertisement for cooking courses": "这是烹饪课程的广告",
    "This is an advertisement for dried meat": "这是干肉的广告",
    "This is an advertisement for knitting advices": "这是针织建议的广告",
    "This is an advertisement for wine kegs": "这是一个酒桶广告",
    "Duration": "持续时间",
    "Sleep": "睡觉",
    "You are fast asleep": "你睡得很熟",
    "Charcoal": "木炭",
    "Coal made from carefuly burning quality wood for lengths of time. This coal cinders for a very long time": "由精心燃烧的优质木材制成的煤炭，可长时间燃烧。 这煤渣很长一段时间",
    "Sleeping Old Man: A customer? Pick what you want": "沉睡的老人：顾客？ 选择你想要的",
    "1, Toughness EXP Gain +3": "1、韧性经验增益+3",
    "Plain round bun, very soft and filling": "纯圆的包子，非常柔软和有馅",
    "Steamed Bun": "包子",
    "You're drenched in water": "你被水淋湿了",
    "Wet": "潮湿",
    "[Spring]": "[春]",
    ") for": ") ",
    "Tasty!": "可口！",
    "Wild Rabbit died": "野兔死了",
    "\"Water Absorption\"": "\"吸水\"",
    "Ability to absorb Water Ki and assimilate it within your body": "能够吸收水气并在体内同化",
    "Provides minor protection from water-based attacks": "对水基攻击提供轻微保护",
    "Reduces energy loss when wet": "减少潮湿时的能量损失",
    "Water Absorption": "吸水",
    "Water Absorption lvl: ": "吸水等级：",
    "\"Sharp Eye\"": "\"锐眼\"",
    "Hard/soft-boiled egg, you aren't sure. Will fill you up either way": "硬/软煮鸡蛋，你不确定。 无论哪种方式都会填满你",
    "Rotten Onigiri": "乐天饭团",
    "This riceball has gone bad. You normally wouldn't eat this, but when you run out of food even this looks delicious": "这个饭团坏了。 你通常不会吃这个，但当你没有食物时，即使这个看起来也很好吃",
    "'Meditation'": "'冥想'",
    "A pungent garlic, popular as a seasoning for its strong flavor": "一种辛辣的大蒜，因其浓郁的味道而作为调味品而广受欢迎",
    "Ability to notice weak points": "发现弱点的能力",
    "Long piece of wood with a sharp metal chunk at the end of it. Couldn't get simpler than that": "一根长木头，末端有一块锋利的金属块。 没有比这更简单的了",
    "Garlic": "大蒜",
    "New Moon": "新月",
    "Sharp Eye": "锐眼",
    "Slightly increases critical probability": "略微增加临界概率",
    "Spear": "矛",
    "Spear/Polearm": "矛/长柄武器",
    "Spear/Polearm, Piercing": "矛/长柄武器，穿刺",
    "\"...I won't lower it further!...\"": "\"......我不会再降低它了！......\"",
    "1, Toughness EXP Gain +3%": "1、坚韧经验获得+3%",
    "Ability to walk": "步行能力",
    "actions": "动作",
    "Storm": "风暴",
    "Sunrise": "日出",
    "Walking": "步行",
    "You learned a new action": "你学会了一个新动作",
    "'Sleeping'": "'睡觉'",
    "\"Run\"": "\“跑\”",
    "\"Walking\"": "\"不行\"",
    "Energy Consumption +0.1": "能耗 +0.1",
    "A c t i o n　　l i s t": "动作列表",
    "Run": "跑",
    "Run within this area to improve your physique": "在该区域内跑步以改善您的体质",
    "This isn't the best place to run around": "这不是跑来跑去的最佳场所",
    "Trains Walking": "训练步行",
    "You start running": "你开始跑步",
    "You stop": "你停下了",
    "Running": "跑步中",
    "You're jogging": "你在慢跑",
    "'Walking'": "'步行'",
    "\"Walker\"": "\"步行者\"",
    "5, New Title": "5, 新称号",
    "All this walking around feels very beneficial for your body": "所有这些走动感觉对你的身体非常有益",
    "Running consumes 5% less energy": "跑步消耗的能量减少 5%",
    "talent effect": "天赋效应",
    "Walker": "步行者",
    "Tiny shield that is supposed to be strapped onto an arm. Low defence, but provides high mobility": "应该绑在手臂上的小盾牌。 低防御，但提供高机动性",
    "Toughness EXP Gain +10%, STR +1, SAT +10, EXP Gain +3%, STR Training Potential +3%": "韧性 经验 增益 +10%，力量 +1，体力 +10，经验 增益 +3%，力量 训练潜力 +3%",
    "Tunic": "束腰外衣",
    "narmed Mastery": "武装精通",
    "War": "战争",
    "Wearable ornament in the shape of a sword. Even if ranking the lowest, it serves as a proof of one's affiliation with dojo and martial arts in general": "剑形的可穿戴装饰品。 即使排名最低，也可以作为证明自己与道场和武术有渊源的证据",
    "Weakest healing potion you can possibly find. Nearly useless for actual healing, but can act as a headache reliever": "你能找到的最弱的治疗药水。 对实际治疗几乎无用，但可以起到缓解头痛的作用",
    "Wide selection of various edible berries collected from the forest": "从森林中收集的各种可食用浆果",
    "Wild Berries": "野生浆果",
    "Wood Effigy": "木雕",
    "\"Book of Fairy Tales\"": "\"童话书\"",
    "\"Checkpoint\"": "\"检查站\"",
    "\"First Aid Manual\"": "\"急救手册\"",
    "\"Herbalist =>\"": "\"草药师 =>\"",
    "\"Street Fighting\"": "\“巷战\”",
    "\"Sweet purchase!\"": "\“甜蜜的购买！\”",
    "\"There ya go, enjoy\"": "\“你去吧，享受\”",
    "|Marketplace, Herbalist|": "|市场，草药师|",
    "1, Pierce DEF +1, New Title": "1、穿刺防御+1，新称号",
    "12, EXP Gain +3%, HP Training Potential +3%": "12、经验增益+3%，生命值训练潜力+3%",
    "12, Pain Resistance EXP Gain +2%": "12、抗痛性经验增益+2%",
    "3%, Pain Resistance EXP Gain +1%": "3%, 抗痛性 经验 增益 +1%",
    "A basic stone bowl and a pounder used to mince and crush herbs, seeds, bones and other pharmaceutical oddities": "一个基本的石碗和一个捣碎器，用于切碎和压碎草药、种子、骨头和其他药品",
    "A handful of acorns, still in their shells. Squirrels like them, but they're not very good for you to eat in this state": "一把橡子，还在壳里。松鼠喜欢它们，但它们在这种状态下不太适合你吃",
    "A simple, short-sleeved shirt. It's somewhat short in length and tailored to snugly fit the wearer's body": "一件简单的短袖衬衫。它的长度略短，并量身定制以紧贴佩戴者的身体",
    "A very long bread": "一个很长的面包",
    "Ability to detect and avoid danger": "发现和避免危险的能力",
    "Ability to fight using blunt weaponry": "使用钝器进行战斗的能力",
    "Ability to fight using polearms and lances": "使用长矛和长矛进行战斗的能力",
    "Ability to safely digest dangerous food": "能够安全地消化危险食物",
    "Ability to use shields better": "能够更好地使用盾牌",
    "Acorn": "橡子",
    "Alchemical vessel used for distilling, important for vapor separation": "用于蒸馏的炼金容器，对蒸汽分离很重要",
    "Alchemy EXP gain +10": "炼金经验增益 +10",
    "Alchemy EXP gain +5": "炼金经验获得+5",
    "Alchemy quality": "炼金品质",
    "All masteries EXP Gain +10": "所有专精经验获得 +10",
    "Alliviates food poisoning": "缓解食物中毒",
    "An amusing collection of folklore featuring the usual cast of fairies and demons": "一个有趣的民间传说集合，以通常的仙女和恶魔为特色",
    "Any sharp tool": "任何锋利的工具",
    "Baguette": "法国面包",
    "Beef Jerky": "牛肉干",
    "Brittle bone of some animal": "一些动物的脆骨",
    "Buckler": "圆盾",
    "Bundle of certain common herbs, mixed together. Tastes incredibly bitter, but helps to detoxify blood from containments": "某些常见草药的捆绑，混合在一起。味道令人难以置信的苦，但有助于从容器中解毒血液",
    "Carrot": "萝卜",
    "Clear blob of slime. Used in elementary alchemy to make adhesives. Also acts as a base for some potions": "清除一团粘液。在初级炼金术中用于制造粘合剂。也可作为某些药水的基础",
    "Dagger": "匕首",
    "Danger Sense": "危险意识",
    "Energy Effectiveness +1%, New Title": "能量效率 +1%，新称号",
    "Fake Sword": "假剑",
    "Grants +2500 EXP": "授予 +2500 经验",
    "Grants invulnerability to poisons for a few hours": "使毒药在几个小时内无敌",
    "Hammer Mastery": "锤子精通",
    "Healing potion with weak healing powers. It is usually used by commoners as first aid before deciding whether to go see a doctor or not": "治疗力较弱的治疗药水。通常被平民在决定是否去看医生之前作为急救使用",
    "Healing Stew": "治愈炖肉",
    "Herbal Antidote": "草本解毒剂",
    "Herbalist": "草药师",
    "Herbalist: Don't neglect your well being, stack on anything you will need": "草药师：不要忽视您的健康，多吃您需要的任何东西",
    "Herbalist: Injured? Come in, I'll give you a check up": "草药师：受伤了？进来我给你检查",
    "Jelly": "果冻",
    "Knife, Edged": "刀，有边",
    "Lesser Healing Potion": "次级治疗药水",
    "Long stick with a sharpened end. Watch out, you may hurt someone with it": "末端锋利的长棍。小心，你可能会用它伤害别人",
    "LUCK +1": "运气+1",
    "lvl:14 'Jogger'": "lvl:14 '慢跑者'",
    "Makes animals love you": "让动物爱你",
    "Mastery of destruction and military tactics": "掌握破坏和军事战术",
    "Mastery of petting animals": "掌握抚摸动物",
    "Mastery of unarmed combat": "掌握徒手格斗",
    "Mid-grade Spirit Pill": "中品灵丹",
    "Minor Healing Potion": "初级治疗药水",
    "Mixture of ginger, bittervine,  and other herbs. Destroys toxins in one's body": "姜、苦藤和其他草药的混合物。清除体内毒素",
    "Mortar and Pestle": "研钵和研杵",
    "Neautralizes the effects of weak poisons": "中和弱毒的效果",
    "Old worthless blade, forgotten for ages. It falls apart as you attempt to swing it": "旧的毫无价值的刀片，被遗忘了多年。当你试图摆动它时它会崩溃",
    "Patting": "拍拍",
    "Patting lvl: 5": "拍打等级：5",
    "Poison Ward": "中毒病房",
    "Polearm M lvl: 5": "长柄武器等级：5",
    "Polearm Mastery": "长柄武器精通",
    "Raw Meat": "生肉",
    "Reduces energy loss from food poisoning": "减少食物中毒造成的能量损失",
    "Retort": "反驳",
    "Roasted Meat": "烤肉",
    "Rusty Katana": "生锈的武士刀",
    "Rusty Key": "生锈的钥匙",
    "Scummy old key. You can open your basement with it": "肮脏的旧钥匙。你可以用它打开你的地下室",
    "Sharpened Stick": "削尖的棍子",
    "Shield Mastery": "盾牌精通",
    "Should you really be eating this stuff?": "你真的应该吃这些东西吗？",
    "Simple knife used by wayfarers. Not a combat weapon, has a minor domestic use": "徒步旅行者使用的简单刀。不是作战武器，在国内有少量使用",
    "Slightly decreases critical damage received": "略微降低受到的暴击伤害",
    "Slightly increases attack power when fighting unarmed": "徒手战斗时稍微增加攻击力",
    "Slightly increases attack power when holding a club/hammer": "持有棍棒/锤子时略微增加攻击力",
    "Slightly increases attack power when holding a spear/polearm": "手持长矛/长柄武器时略微增加攻击力",
    "Slightly increases crit damage": "略微增加暴击伤害",
    "Slime": "粘液",
    "Small Bone": "小骨头",
    "Small cheap spirit pill, made from condensed Ki. Developed to help young martial artists to go through their training": "小巧廉价的灵丹，由气凝聚而成。旨在帮助年轻的武术家完成他们的训练",
    "Solution developed to protect residents from diseases during times of plague": "开发解决方案以在鼠疫期间保护居民免受疾病侵害",
    "Stomach Medicine": "胃药",
    "Straw Effigy": "稻草人像",
    "Survival": "生存",
    "Sword Medal": "剑勋章",
    "Sword, Edged": "剑，刃",
    "The sword is made of bamboo. Poorer ronin sometimes pretend to be full-fledged samurai with this": "剑是竹制的。可怜的浪人有时会用这个假装是成熟的武士",
    "This is a well illustrated fairy tale about a war between the birds and the beasts, with particulars on the wartime conduct and eventual fate of the bat.": "这是一个关于鸟与野兽之间战争的精美童话故事，详细介绍了蝙蝠的战时行为和最终命运。",
    "Tiny red pocket-sized guide to emergency care, covers basic bandaging and wound treating": "红色袖珍版急救护理指南，涵盖基本的包扎和伤口治疗",
    "\"...mama!!...\"": "\"...妈妈!!...\"",
    "\"<= Escape\"": "\"<= 逃脱\"",
    "\"Challenge a dangerous opponent\"": "\"挑战一个危险的对手\"",
    "\"Check on Cat\"": "\"查看猫\"",
    "\"Decline\"": "\“拒绝\”",
    "\"Enter the basement\"": "\"进入地下室\"",
    "\"Pet Cat\"": "\“宠物猫\”",
    "\"Rename\"": "\"重命名\"",
    "\"You are facing a golem\"": "\"你面对的是一个傀儡\"",
    "| Color": "| 颜色",
    "Actually give it a name, maybe?": "实际上给它一个名字，也许？",
    "|Your Home, Basement|": "|您的家，地下室|",
    "Age": "年纪",
    "And": "和",
    "Argh! This place is infested!": "啊！ 这个地方出没！",
    "Bat": "蝙蝠",
    "can't rename later!": "以后不能重命名！",
    "Cat ♀": "猫 ♀",
    "Day of birth": "出生日期",
    "Days": "天",
    "Fawn": "讨好",
    "Fluffy": "蓬松的",
    "Give your cat a name!": "给你的猫起个名字！",
    "Great way to pass time. Your cat is resting next to you": "打发时间的好方法。 你的猫在你旁边休息",
    "Hiding": "隐藏",
    "Its Master": "它的主人",
    "Likes": "喜欢",
    "Lookout Guard: If you want work come at the time that's stated in the notice and not a minute late!": "了望卫队：如果你想上班，请按通知中规定的时间来，不要迟到一分钟！",
    "Months": "月",
    "Name": "名字",
    "Paper Golem": "纸傀儡",
    "Pattern": "图案",
    "You feel safe. You can rest here.": "你感到安全。 你可以在这里休息。",
    "You feel safe. You can rest here. Meow": "你感到安全。 你可以在这里休息。 喵",
    "You feel safe. You can rest here. You hear rustling": "你感到安全。 你可以在这里休息。 你听到沙沙声",
    "Great way to pass time. You feel warm": "打发时间的好方法。 你感到温暖",
    "Running consumes 15% less energy": "跑步消耗的能量减少 15%",
    "Simply walking doesn't cut it anymore, maybe you should speed up a bit while travelling on foot?": "单纯走路已经不行了，也许你应该在步行时加快一点？",
    "\"=> Hunt indefinitely\"": "\"=> 无限期狩猎\"",
    "Cyan": "青色",
    "Western Woods, They're Nearby": "西部森林，他们就在附近",
    "\"Monster eradication\"": "\“消灭怪物\”",
    "\"Sell firewood": "\"卖柴火",
    "Cyan Slime": "青色史莱姆",
    "Don't even think about it, you will not be sent to your death. Go back and train, dojo has everything you need": "想都别想，你不会被送死的。 回去训练，道场有你需要的一切",
    "I'll fetch you 15 copper per bundle! How many do you want to sell?": "一包15铜给你！ 你想卖多少？",
    "Perfectly dried strips of meat. The taste is not bad, this jerky can be kept edible for years": "完全干燥的肉条。 味道还不错，这个肉干可以保存多年",
    "Getting beat up like this hurts like hell. You better think of a way out of this misery!": "像这样被殴打真是太痛苦了。 你最好想办法摆脱这种痛苦！",
    "Lesser slimes, devoid of any senses. They survive by absorbing debris from the ground": "较小的史莱姆，没有任何感官。 它们靠吸收地面上的碎片生存",
    "Punching Bag": "沙袋",
    "Unarmed Mastery": "徒手精通",
    "Durability of one's body": "身体的耐久性",
    "Edible part of some animal, has to be cooked before consumption": "某些动物的可食用部分，食用前必须煮熟",
    "Rusty Dagger": "生锈的匕首",
    "Slightly improves physical defence": "小幅提升物理防御",
    "Small wooden doll with flexible joints. This type can be used, with Dark enchantment, to take control of living things.": "带有灵活关节的小木娃娃。 这种类型可以与黑暗附魔一起使用来控制生物。",
    "SPCL": "特殊",
    "Used up useless knife. More of a blunt weapon in it's current state": "用完没用的刀。 在当前状态下更像是一种钝器",
    "Toughness": "韧性",
    "15, HP +30, Gluttony EXP Gain +5%": "15、生命值 +30、暴食经验增加+5%",
    "3%, Pain Resistance EXP Gain +5%, New Title": "3%，抗痛经验获得 +5%，新称号",
    "5%, STR +1, Drinking EXP Gain +10%, New Title": "5%, 力量 +1, 饮酒经验增加 +10%, 新称号",
    "5%, Toughness EXP Gain +10%": "5%, 坚韧 经验 增益 +10%",
    "Toppling objects": "倾倒对象",
    "Tricolored": "三色",
    "You feel safe. You can rest here. Your cat comes out to greet you!": "你感到安全。 你可以在这里休息。 你的猫出来迎接你！",
    "Your best feline friend": "你最好的猫科动物朋友",
    "\"Challenge a stronger opponent\"": "\“挑战更强大的对手\”",
    "Straw Golem": "稻草魔像",
    "Straw Golem ->": "稻草魔像 ->",
    "Straw Golem -> x2(": "稻草魔像 -> x2(",
    "\"<= Take it back\"": "\"<= 拿回去\"",
    "\"Do your job well and you will be rewarded\"": "\"做好你的工作，你会得到回报\"",
    "\"Nooooo it's ugly!!\"": "\“不不不不不不 太丑了！！\”",
    "\"Show Xiao Xiao a wooden doll\"": "\"给 小小 看一个木偶\"",
    "\"The Hunter Association offers you a large variety of boxes full of smoked meat and furs\"": "\“猎人协会为您提供种类繁多的装满熏肉和毛皮的盒子\”",
    "\"What is it what is it?\"": "\"它是什么它是什么？\"",
    "\"Xiao Xiao =>\"": "\"小小 =>\"",
    "All the time you had to consume disgusting rotten stuff is finally paying off... Kind of. You would rather avoid doing that in the future, if possible": "你不得不消耗令人作呕的腐烂东西的所有时间终于得到了回报......有点。 如果可能的话，你宁愿在未来避免这样做",
    "Garbage Eater": "垃圾吞噬者",
    "Heavy rain": "倾盆大雨",
    "It's pouring so hard the streets are completely flooded. There's noone around except for a few kids": "倾盆大雨，街道完全被淹。 除了几个孩子，周围没有人",
    "There is a report of a missing cat": "有一只猫失踪的报告",
    "This is an advertisement for cleaning services": "这是清洁服务的广告",
    "This is an advertisement for dojo membership": "这是道场会员的广告",
    "This is an advertisement for hemp clothing": "这是一则麻衣广告",
    "This is an advertisement for joining the militia": "这是加入民兵的广告",
    "This is an advertisement for wooden furniture": "这是木制家具的广告",
    "Xiao Xiao": "小小",
    "\"Glass Bones\"": "\"玻璃骨头\"",
    "Bizzarely, you got yourself knocked out by the weakest enemy in existence. How did that happen? You feel like you have achieved somewhat absurd understanding of how frail your body actually is. Perhaps violence isn't for you": "奇怪的是，你被现存最弱的敌人击倒了。 那是怎么发生的？ 你觉得你对自己的身体实际上有多虚弱有了一些荒谬的理解。 也许暴力不适合你",
    "Glass Bones": "玻璃骨头",
    "Mon.": "我的。",
    "\"Be bored\"": "\"无聊\"",
    "*whistle*": "*吹口哨*",
    ", AGL +1": ", 敏捷 +1",
    "1, Pain Resistance EXP Gain +3%": "1、抗痛性经验增益+3%",
    "1, Pain Resistance EXP Gain +7%, New Title": "1、抗痛性经验获得+7%，新称号",
    "5%, Energy Effectiveness +1%, New Title": "5%, 能量效率 +1%, 新称号",
    "5%, STR +1, New Title": "5%, 力量 +1, 新称号",
    "Penny of Wealth": "一分钱财",
    "Perception": "洞察力",
    "Picking a coin gives you an extra coin": "选择一枚硬币会给你一个额外的硬币",
    "Pine Nuts": "松子",
    "Prevents you from getting rained on": "防止你淋雨",
    "Provides minor protection from fire-based attacks": "提供轻微的保护以免受基于火的攻击",
    "Rabbit Foot": "兔脚",
    "Raises stats during day": "提高白天的统计数据",
    "Reduces chances to cook a failed product": "减少烹饪失败产品的机会",
    "Regular carrot, boiled in water. It is sweet but not all that tasty, actually": "普通胡萝卜，在水中煮沸。它很甜，但不是那么好吃，实际上",
    "Right...": "对...",
    "Scrambled Eggs": "炒鸡蛋",
    "Simple slab of meat, roasted on an open fire without any seasoning. Tastes pretty good nonetheless": "简单的肉块，在明火上烤，不加任何调味料。不过味道还不错",
    "Simple square shield with reinforced corners": "带加强角的简单方形盾牌",
    "Skill of chances": "机会技能",
    "Slightly shifts shop prices in your favour": "稍微调整商店价格对您有利",
    "Small handcrafted straw doll. Dolls of this type are used to bind with the souls of the living. Appropriate for Curses and Dark Magic manipulation": "手工制作的小草娃娃。这种类型的娃娃用于与活人的灵魂结合。适用于诅咒和黑魔法操作",
    "Somewhat stops bleeding": "有点止血",
    "Soul Puppet": "魂傀",
    "Stake Shield": "桩盾",
    "Stamina Jelly": "耐力果冻",
    "Sun blessing": "赞美太阳",
    "Sun Charm": "阳光魅力",
    "Targe": "目标",
    "Tasteless soup made by boiling heaps of cure grass in water. Healing only in name, it is known that exposing cure grass to high temperatures destroys any healing properties of the product": "将成堆的治疗草在水中煮沸制成的无味汤。只是名义上的愈合，众所周知，将治疗草暴露在高温下会破坏产品的任何愈合特性",
    "The art of Cooking": "烹饪艺术",
    "The art of Creation": "创造的艺术",
    "The power of possessions": "财产的力量",
    "There doesn't seem to be anything of interest around..": "周围好像没什么兴趣。。",
    "This is boring": "这很无聊",
    "Thoroughly examine current area in search for hidden passages, treasure, secrets or anything of interest": "彻底检查当前区域以寻找隐藏的通道、宝藏、秘密或任何感兴趣的东西",
    "Toolbox": "工具箱",
    "Tough leather gauntlet that covers your entire hand. May prevent you from losing fingers": "坚固的皮革手套，覆盖您的整只手。可以防止你失去手指",
    "Trading": "贸易",
    "Umbrella": "伞",
    "Village Center, Marketplace Entry Gate": "村中心、市场入口",
    "Yarn Ball": "纱球",
    "Yawn..": "打哈欠..",
    "Yeah...": "是的...",
    "You are blessed by Sun": "你被太阳祝福",
    "You are standing on guard duty. This isn't very fun": "你正在值班。这不是很有趣",
    "You begin to look around": "你开始环顾四周",
    "A handful of tasty crunchy nuts from a pinecone": "一把松果中的美味松脆坚果",
    "A passerby dropped a coin. Sweet!": "一个路人丢了一枚硬币。甜的！",
    "A proof of loyalty brought to you by your cat": "您的猫给您带来的忠诚证明",
    "A small doll carved from beast bone. It's a charm that protects the wearer from evil": "用兽骨雕刻而成的小人偶。是保护佩戴者免受邪恶侵害的护身符",
    "A-Z": "A-Z",
    "Ability to absorb Fire Ki and assimilate it within your body": "能够吸收 Fire Ki 并将其吸收到体内",
    "Ability to exchange wealth for goods and services": "用财富换取商品和服务的能力",
    "Ability to find and collect usable materials from the surroundings": "能够从周围寻找和收集可用材料",
    "Ability to see the unseen and better understand your surroundings": "能够看到看不见的事物并更好地了解周围环境",
    "Adhesive Bandage": "粘性绷带",
    "Ah...": "啊...",
    "Alchemy": "炼金术",
    "Allows deconstruction of items and equipment when kept in inventory": "允许在库存中分解物品和设备",
    "An extra shiny penny, that looks like it's made of gold. It probably isn't, but you feel richer just by holding it": "一个额外闪亮的便士，看起来像是用金子做的。可能不是，但只要持有它，你就会感觉更富有",
    "Bandage, boiled in hot water and sterilized using herbs": "绷带，在热水中煮沸并用草药消毒",
    "Bleed resist +5": "流血抗性 +5",
    "Boiled Carrot": "水煮胡萝卜",
    "Bone Doll": "骨娃娃",
    "Burnt Meat": "烧肉",
    "Clean piece of thin sturdy cloth, perfect for wrapping and securing open wounds": "干净的一块坚固的薄布，非常适合包裹和固定开放的伤口",
    "Coal-looking overcooked chunk of meat. Mildly nutritious but awful to eat": "像煤炭一样煮熟的大块肉。有点营养，但吃起来很糟糕",
    "Common edible mushroom. When cooked with the right ingredients, the flavour of this mushroom is not so common": "常见的食用菌。当用正确的原料烹制时，这种蘑菇的味道并不那么常见",
    "Concentrated green jelly. Improves stamina": "浓缩的绿色果冻。提高耐力",
    "Cooking": "烹饪",
    "Crafting": "制作",
    "Dead Bird": "死鸟",
    "Deconstruct": "解构",
    "Disassemble": "拆卸",
    "Dolls that could be remotely controlled by one's soul. Employed by spies to infiltrate enemy lines unnoticed": "可以被灵魂遥控的人偶。被间谍雇佣以潜入敌军，不被发现",
    "Family Heirloom": "传家宝",
    "Family Heirloom+": "传家宝+",
    "Fire Absorption": "吸火",
    "Fluffy and delicious scrambled eggs": "松软可口的炒鸡蛋",
    "Fluffy ball of yarn which is normally used as a material for knitting. Cats love these and often claim them as toys": "蓬松的纱线球，通常用作针织材料。猫喜欢这些并经常声称它们是玩具",
    "Fluffy rice. Simple dish that tastes good": "蓬松的米。简单的菜，味道不错",
    "Gambling": "赌博",
    "Gauntlet": "护手",
    "Greed": "贪婪",
    "Harvesting": "收获",
    "Increases chances of obtaining area loot": "增加获得区域战利品的机会",
    "into": "进入",
    "Investigate": "调查",
    "It gets very sweet when boiled": "煮的时候很甜",
    "Knowledge of medicine and alchemical transmutation": "医学和炼金术的知识",
    "L": "升",
    "Life Shard": "生命碎片",
    "Light umbrella with a cloud pattern. Young masters and ladies carry these to display their carefree nature": "带有云纹的光伞。少爷女士们随身带着这些，彰显洒脱的本性",
    "Little charm with a piece of power of the Sun imbued into it. It absorbs Sun energy": "带着一丝太阳之力的小符咒。它吸收太阳能",
    "Lookout Guard: Work's done for today, you have performed your duty just well and earned your salary, take it. You are advised to go straight home after you check out": "守望者：今天的工作已经完成了，你尽职尽责，拿到了工资，拿去吧。建议您退房后直接回家",
    "Lucky charm made from a foot of a rabbit. Wearing this gives you a strange feeling of satisfaction": "由一只兔子的脚制成的幸运符。穿上它，让你有一种莫名的满足感",
    "Makes autocrafting faster": "使自动制作更快",
    "Metal box with a variety of fine tools inside, multipurpose knives, mallets, pincers, chisels and a few more. Used for precision work and tinkering with simple and complex objects": "金属盒，里面有各种精美的工具、多用途刀、木槌、钳子、凿子等等。 用于精密工作和修补简单和复杂的物体",
    "Mushroom": "蘑菇",
    "Not actually a shield, but a row of spiky wood stakes tightly packed together to form a square panel. It's a bit heavy": "实际上不是盾牌，而是一排尖尖的木桩紧紧地挤在一起形成一个方板。 有点重",
    "Nothing in the box yet": "盒子里还没有东西",
    "Rotten Meat": "腐烂的肉",
    "Spotted": "斑点",
    "Unarmed STR": "手无寸铁的力量",
    "Storage Box": "储物盒",
    "You reinforced your family pendant's string with straw to prevent possible breaking. It looks even more lame like this": "你用稻草加固了家庭吊坠的绳子，以防止可能的断裂。 这样看起来更蹩脚",
    "\"Access Storagebox\"": "\"存取储物箱\"",
    "\"<= Step Away\"": "\"<= 走开\"",
    "\"Poison Resistance\"": "\"抗毒\"",
    "\"Toss some firewood into the fireplace\"": "\"往壁炉里扔些柴火\"",
    "|Your Home, Storage Box|": "|您的家，储物箱|",
    "A knife originally used to cut fish, not people. It's not a sword, but ordering one won't get you yelled at": "刀原本是用来切鱼的，不是用来切人的。 这不是剑，但订购一把不会让你大吼大叫",
    "A sword designed for mass production by reducing labor and material cost down to a minimum. It may look like a sword, but it's not really fit to cut anything. The manual suggests it be used to cut radishes": "通过将劳动力和材料成本降至最低而设计用于大规模生产的剑。 它看起来像一把剑，但它并不适合切割任何东西。 说明书上建议用来切萝卜",
    "Attic spider": "阁楼蜘蛛",
    "Being brushed": "被刷",
    "Cat": "猫",
    "Dull Sword": "钝剑",
    "Greenish grey organic mass that was once something edible, now isn't good for pretty much anything": "曾经是可食用的绿灰色有机物质，现在几乎不适合任何东西",
    "Huge container with a secure padlock. You can put your possessions inside to keep them safe.": "带有安全挂锁的巨大容器。 你可以把你的财物放在里面以保证它们的安全。",
    "Kitchen Knife": "菜刀",
    "Knuckles": "指关节",
    "Leather bands that cover fingers": "覆盖手指的皮带",
    "Master's bed": "主人的床",
    "Alembic": "阿朗比克",
    "Candle": "蜡烛",
    "Dangerous beasts were sighted in vicinity of the Southern Forest. These reports are likely linked to the cause of livestock and locals getting injured, therefore, to avoid further casualties, entry into the forest is prohibited to those without permit or high enough self-defence ability until the situation is resolved": "南方森林附近出现了危险的野兽。 这些报告很可能与牲畜和当地人受伤有关，因此，为避免进一步伤亡，在情况解决之前，没有许可证或具有足够自卫能力的人禁止进入森林",
    "Herbalist: Yes yes..": "草药师：是的，是的..",
    "It says here": "它说这里",
    "Looking for a anyone with free time to assist local militia with guarding duty. Apply at the checkpoint near marketplace area between 7AM and 10AM\"": "寻找任何有空闲时间的人来协助当地民兵执勤。 早上 7 点到 10 点在市场附近的检查站申请\"",
    "Pathetic": "可怜的",
    "Your weak punch can barely exert a power of 100kg, which is a measly amount in the martial world. A simple farmer can hit harder than this": "你那一拳微弱的力量，勉强能发挥出一百公斤的威力，这在武林中是微不足道的。 一个简单的农民可以打得比这更重",
    "\"Huh..\"": "\“嗯..\”",
    "\"I see\"": "\“我懂了\”",
    "\"Pathetic\"": "\“可怜的\”",
    "\"Sword Medal\"": "\"剑勋章\"",
    "\"Warning!\"": "\“警告！\”",
    "一Head of The Guard, Hitoshi": "一警卫队长仁志",
    "A tall wax candle, made to burn for a very long time": "一根高大的蜡烛，可以燃烧很长时间",
    "Alchemical vessel used in distilling, especially useful for cooling": "用于蒸馏的炼金容器，特别适用于冷却",
    "Amber": "琥珀色",
    "Bamboo Training Sword": "竹练剑",
    "Herbalist: Yes indeed, if you have any cure grass to sell, by all means bring it here, you can never have too much. I will take bundles of 50 for 15": "草药师：是的，如果你有任何治疗草要卖，一定要带过来，你永远不会有太多的。 我要一包 50 个 15 个",
    "High-grade Spirit Pill": "上品灵丹",
    "Looks like a page from someone's notebook, marked \"H\", poorly written in bad handwriting. It lists several simple things you can cook and make from widely available cheap materials": "看起来像是某人笔记本上的一页，标有“H”，字迹不佳。 它列出了一些简单的东西，你可以用广泛可用的廉价材料烹饪和制作",
    "Bag Of Bones": "骨头袋",
    "Pinecone": "松果",
    "Small spirit pill, made from condensed Ki. Given to young warriors as energy supplement": "小灵丸，由气凝聚而成。 送给年轻战士作为能量补充",
    "Vitamins": "维生素",
    "\"<= Rather not\"": "\"<= 而不是\"",
    "\"Guide To Living By Yourself\"": "\“独自生活指南\”",
    "\"Sell cure grass": "\"卖治愈草",
    "\"Sell your goods\"": "\"卖你的货\"",
    "[Summer]": "[夏]",
    "A bottle of powerful vitamins, which grant one's body incresed vitality": "一瓶强效维生素，增强身体活力",
    "A training sword for kenjutsu lessons. Designed in the late Edo period, it is strung together from four bamboo planks. The ruthless chief of a female bandit group named Danfu is known to wield it": "剑术课的练剑。 江户时代后期设计，由四块竹板串成。 众所周知，一个名叫丹芙的女强盗团伙的无情头目挥舞着它",
    "A spiny pod from a pine tree.  Dry seeds rattle around inside when you shake it": "松树上的多刺豆荚。 当你摇动它时，干燥的种子会在里面发出嘎嘎声",
    "A very short manual filled with illustrations about primitive dollmaking. The instructions are easy to understand so children could make the dolls too. Looks like there was a chapter dedicated to sewing, now it's almost entirely missing": "一本非常简短的手册，里面有关于原始玩偶制作的插图。 说明很容易理解，所以孩子们也可以制作娃娃。 好像有一章专门讲缝纫的，现在几乎完全没有了",
    "3%, INT +1, New Title": "3%, 智力 +1, 新称号",
    "1, AGL +1": "1, 敏捷 +1",
    "A fragment of living energy, trapped within a crystallic shell. Absorbing these slightly increases lifespan": "被困在水晶壳中的生命能量碎片。吸收这些会略微延长寿命",
    "Ability to endure forms of suffering without complaint": "能够毫无怨言地忍受各种形式的痛苦",
    "All Masteries EXP Gain +5%, Fighting EXP Gain +5%, New Title": "所有精通经验增益 +5%，格斗经验增益 +5%，新称号",
    "Apple Juice": "苹果汁",
    "Awful sandwich that doesn't taste like anything. It is filling, at the very least": "可怕的三明治，尝起来不像任何东西。它正在填充，至少",
    "Bone Cracker": "骨饼干",
    "Bones of some kind, baked until crisp": "某种骨头，烤至酥脆",
    "Coat stitched together from patches of cloth of various sizes and thickness. Somewhat durable but looks desperate": "用不同尺寸和厚度的布块缝合在一起的外套。有点耐用但看起来很绝望",
    "Crude attempt at pants, very baggy looking and somewhat uncomfortable to wear. Potential holes near stitch areas make your lower body shiver when it's windy": "对裤子的粗暴尝试，看起来很宽松，穿起来有点不舒服。缝合区域附近的潜在孔洞使您的下半身在刮风时颤抖",
    "Dead Mouse": "死老鼠",
    "Fighting EXP Gain +10%, New Title": "战斗经验获得 +10%，新称号",
    "Freshly-squeezed from real apples!": "从真正的苹果新鲜挤压！",
    "Increases HP by +2 permanently": "生命值永久 +2",
    "Jelly Sandwich": "果冻三明治",
    "Juice Pulp": "果汁浆",
    "Left-over byproduct from juicing the fruit.  Not very tasty, but contains a lot of healthy fiber": "榨汁后剩下的副产品。不是很好吃，但含有大量健康纤维",
    "More like a healthy dose of dry grass in a sack. Uneven, hard, itchy, and probably bad for your neck. Despite that, it still passes as a basic tool of comfort": "更像是一袋健康剂量的干草。不均匀、坚硬、发痒，可能对你的脖子有害。尽管如此，它仍然作为一种基本的舒适工具",
    "More like a long sheet of cloth folded trice and stitched in. Barely offers any warmth, but keeps you from getting frostbites if it's windy": "更像是一张折叠三折并缝合的长布。几乎不能提供任何温暖，但可以防止刮风时被冻伤",
    "Patchwork Coat": "拼布大衣",
    "Patchwork Pants": "拼布裤",
    "Patience": "耐心",
    "Perception EXP Gain +5%, Critical Damage +2%, EXP Gain +6%": "感知 EXP 获得 +5%，暴击伤害 +2%，EXP 获得 +6%",
    "Ragwork Blanket": "碎花毯",
    "Straw Pillow": "稻草枕",
    "Vermin hunted by your cat, now proudly displayed before you": "被您的猫猎杀的害虫，现在自豪地展示在您面前",
    "\"...break time!...\"": "\“...休息时间！...\”",
    "\"...I'll come back, just wait for a minute...\"": "\"......我会回来的，你等一下......\"",
    "\"...right, I'll take 4, put them in...\"": "\"...对了，我拿4个，放进去...\"",
    "\"...she'll return shortly. As for you...\"": "\"......她很快就会回来。至于你......\"",
    "\"...stop pushing!...\"": "\"...别再推了！...\"",
    "\"...turn right and then...\"": "\"...右转然后...\"",
    "\"...what a scam...\"": "\"...真是个骗局...\"",
    "\"...why is this so expensive?...\"": "\"...为什么这么贵？...\"",
    "\"...yeah, he said it's there...\"": "\“......是的，他说它在那里......\”",
    "\"Dead Mouse\"": "\“死老鼠\”",
    "\"Dollmaker's Handbook\"": "\“玩偶手册\”",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "MED": "药",
    "MAT": "材料",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "???: ": "???: ",
    "/ dodge chance: ": "/ 闪避几率：",
    "Critical chance: ": "暴击几率: ",
    "INT: ": "智力: ",
    "hp: ": "生命值: ",
    "SPD: ": "速度: ",
    "rank: ": "段位: ",
    "STR: ": "力量: ",
    "Straw dummy": "稻草人偶",
    "exp: ": "经验: ",
    "AGL: ": "敏捷: ",
    "Area: Somewhere ": "地区：某处 ",
    "Area: Training Grounds ": "区域：训练场",
    "Last save: ": "上次保存 ",
    "Class: ": "类型: ",
    "Rarity: ": "稀有度: ",
    "DEF: ": "防御: ",
    "lvl: ": "等级: ",
    "There is a cat. Pets: ": "有一只猫。 宠物：",
    "　exp: ": "　经验: ",
    "Famine lvl: ": "饥荒等级：",
    "Leveled Up: ": "升级：",
    "Rank: ": "段位: ",
    "Sleeping lvl: ": "睡眠等级：",
    "| AGL +": "| 敏捷 +",
    "| HP +": "| 生命值 +",
    "| INT +": "| 智力 +",
    "EXP: ": "经验: ",
    "Leveled Up ": "升级 ",
    "STR +": "力量 +",
    "Sword Mastery EXP gain +": "剑精通经验获得+",
    "Literacy EXP gain +": "读写经验增益 +",
    "AGL +": "敏捷 +",
    "EXP Gain +": "经验增益 +",
    "Fighting lvl: ": "战斗等级: ",
    "Gluttony lvl: ": "暴食等级：",
    "HP +": "生命值 +",
    "INT +": "智力 +",
    "Literacy lvl: ": "识字等级：",
    "Meditation lvl: ": "冥想等级：",
    "Pain Resistance lvl: ": "抗痛等级：",
    "SAT +": "SAT +",
    "Perk lvl ": "特权等级 ",
    "SPD +": "速度 +",
    "Death lvl: ": "死亡等级: ",
    "Knife M lvl: ": "刀法精通等级：",
    "Sword M lvl: ": "剑术精通等级: ",
    "Tailoring EXP Gain +": "裁缝经验增益 +",
    "\"Instructor: For all your stuff I can fetch you": "\"指导员：你所有的东西给我，我可以给你 ",
    "Air Absorption lvl: ": "空气吸收等级：",
    "Area: Western forest hunting area / ": "面积：西部森林狩猎区",
    "Judgement lvl: ": "判断等级：",
    "Duration: ": "持续时间：",
    "Sharp Eye lvl: ": "锐眼等级：",
    "Water Absorption lvl: ": "吸水等级：",
    "Walking lvl: ": "步行等级: ",
    "Exp +": "经验 +",
    "Unarmed M lvl: ": "徒手精通 等级：",
    "War lvl: ": "战争等级: ",
    "Danger Sense lvl: ": "危险感知等级：",
    "Shield M lvl: ": "盾牌精通等级: ",
    "Survival lvl: ": "生存等级：",
    "Hammer M lvl: ": "锤子精通等级：",
    "Area: Your basement / ": "区域：您的地下室 /",
    "Blunt DEF +": "钝器防御 +",
    "Edged DEF +": "边缘防御 +",
    "Piercing DEF +": "穿刺防御 +",
    "Patience lvl: ": "耐心等级：",
    "Toughness lvl: ": "韧性等级：",
    "Passive Patting EXP +": "被动拍击经验 +",
    "Patting EXP gain +": "拍打经验增益 +",
    "Patting lvl: ": "拍击等级: ",
    "Perception lvl: ": "认知等级：",
    "Physical ATK +": "物理攻击+",
    "Physical DEF +": "物理防御 +",
    "Polearm M lvl: ": "长柄武器精通等级：",
    "Trading lvl: ": "交易等级：",
    "Dark RES +": "深红+",
    "Danger Sense EXP Gain +": "危机感经验增益 +",
    "Crafting lvl: ": "工艺等级: ",
    "Cooking lvl: ": "烹饪等级: ",
    "Alchemy lvl: ": "炼金术等级：",
    "Gambling lvl: ": "赌博等级：",
    "Fire Absorption lvl: ": "火焰吸收等级：",
    "Greed EXP gain +": "贪婪经验增益 +",
    "Evil Class DEF +": "邪恶职业防御 +",
    "Greed lvl: ": "贪婪等级：",
    "Harvesting lvl: ": "收获等级：",
    "LUCK +": "幸运 +",
    "Max SAT +": "最大SAT +",
    "MAX SAT +": "最大SAT +",
    "Cooking EXP gain +": "烹饪经验增益 +",
    "MAX HP +": "最大生命值 +",
    "Alchemy EXP gain +": "炼金经验获得 +",
    "Poison resist +": "毒抗+",
    "Tailoring tool lvl: ": "裁缝工具等级：",
    "Sleep EXP gain +": "睡眠经验增益 +",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "OFF": "关闭",
    " Throwing Damage": " 投掷伤害",
    " Items returned back to dojo": " 物品退回道场",
    "Buying price": "购买价格",
    "Reputation": "名声",
    " Slime died": " 史莱姆死了",
    " Slime missed": "史莱姆未命中",
    " Slime ->": " 史莱姆 ->",
    " Slime -> x2(": " 史莱姆 -> x2(",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^x(\d+)$/,
    /^\/ (\d+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+)\:([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+)\:([\d\.]+)\:([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^\-([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/(.+)$/,
    /^([\d\.,]+)\/([\d\.,]+)\/([\d\.,]+) ([\d\.,]+):([\d\.,]+)  $/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^lvl:(.+) \'Beast (.+)\'$/, '等级:$1 \'野兽 $2\''],
    [/^lvl:(.+) \'Evil (.+)\'$/, '等级:$1 \'邪恶 $2\''],
    [/^lvl:(.+) \'Glass Bones\'$/, '等级:$1 \'玻璃骨头\''],
    [/^lvl:(.+) \'Iron Stomach\'$/, '等级:$1 \'铁胃\''],
    [/^lvl:(.+) \'Garbage Eater\'$/, '等级:$1 \'垃圾吞噬者\''],
    [/^lvl:(.+) \'Bag Of Bones\'$/, '等级:$1 \'骨头袋\''],
    [/^lvl:(.+) \'Pathetic\'$/, '等级:$1 \'可怜的\''],
    [/^lvl:(.+) \'Aspiring Ronin\'$/, '等级:$1 \'有抱负的浪人\''],
    [/^lvl:(.+) \'Starving Child\'$/, '等级:$1 \'饥饿的孩子\''],
    [/^lvl:(.+) \'Punching Bag\'$/, '等级:$1 \'沙袋\''],
    [/^lvl:(.+) \'Thrasher\'$/, '等级:$1 \'长尾鲨\''],
    [/^lvl:(.+) \'Illiterate\'$/, '等级:$1 \'文盲\''],
    [/^lvl:(.+) \'Walker\'$/, '等级:$1 \'步行者\''],
    [/^lvl:(.+) \'Prick\'$/, '等级:$1 \'刺\''],
    [/^lvl:(.+) \'Civilian\'$/, '等级:$1 \'平民\''],
    [/^lvl:(.+) \'Scrawny\'$/, '等级:$1 \'骨瘦如柴\''],
    [/^lvl:(.+) \'Initiate\'$/, '等级:$1 \'开始\''],
    [/^lvl:(.+) \'Nobody\'$/, '等级:$1 \'没有人\''],
    [/^Restored (.+) hp$/, '恢复 $1 生命值'],
    [/^Restored (.+) energy$/, '恢复 $1 能量'],
    [/^energy: (.+) eff: (.+)$/, '能量：$1 效率：$2'],
    [/^Grants (.+) EXP$/, '授予 $1 经验'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^\"Notice \#([\d\.]+)\"$/, '\"注意 \#$1\"'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^lvl ([\d\.]+)$/, '等级 $1'],
	[/^([\d\.]+), EXP Gain \+([\d\.]+)\%$/, '$1、经验增益\+$2\%'],
	[/^([\d\.]+), EXP Gain \+([\d\.]+)\%, New Title$/, '$1，经验增益\+$2\%, 新称号'],
	[/^([\d\.]+), SAT \+([\d\.]+), New Title$/, '$1，SAT \+$2, 新称号'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+), HP \+(\d+)$/, '$1, 生命值 \+$2'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);