name: timer
on: 
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  update:
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3
          with:
            ref: 'originwebsite'
        - name: Download files
          run: |
            curl https://23html.github.io/ -s -S -o index.html --connect-timeout 20 --retry 10 --retry-delay 10
            curl https://23html.github.io/ctst.png -s -S -o ctst.png --connect-timeout 20 --retry 10 --retry-delay 10
            curl https://23html.github.io/changelog/ -s -S -o changelog.html --connect-timeout 20 --retry 10 --retry-delay 10
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add -A
            git diff-index --quiet HEAD && echo "no update" || (echo "update!" && git commit -m 'update' && git push origin originwebsite)
            
